# .github/workflows/deploy.yml
name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/test-task-inforce

            # Get the latest updates
            git pull origin main

            # Install new dependencies
            npm install --production

            # Restart the app
            pm2 restart inforce-api

            # Save PM2 status
            pm2 save

            echo "Deployment completed successfully!"